Failure # 1 (occurred at 2021-05-24_11-15-50)
Traceback (most recent call last):
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py", line 1481, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=53382, ip=192.168.2.103)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=53382, ip=192.168.2.103)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 339, in _inner
    inner(config, checkpoint_dir=None)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 330, in inner
    trainable(config, **fn_kwargs)
  File "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py", line 32, in training_function
    trainer.fit(model)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 489, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 729, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 424, in optimizer_step
    model_ref.optimizer_step(
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 329, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 193, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 723, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 812, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 280, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 155, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py", line 60, in training_step
    self.logger.experiment.log_param(key='layer_2_size', value=self.layer_2_size)
TypeError: log_param() missing 1 required positional argument: 'run_id'

