{
  "checkpoints": [
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"6289b_00000\",\n  \"config\": {\n    \"lr\": 0.0003296942511968579,\n    \"batch_size\": 32,\n    \"mlflow\": {\n      \"experiment_name\": \"/Users/timo.bohnstedt@fau.de/Jiggsaw_test\",\n      \"tracking_uri\": \"databricks\"\n    }\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"lr\": 0.0003296942511968579,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"0_batch_size=32,lr=0.00032969\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 8,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b088c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1624033353.0815291,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_6289b_00000_0_batch_size=32,lr=0.00032969_2021-06-18_18-22-33\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_6289b_00000_0_batch_size=32,lr=0.00032969_2021-06-18_18-22-33/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 718, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 688, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 62, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1494, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=66635, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 501, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 451, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 563, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=66635, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 340, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 331, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 40, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\\\", line 489, in safe_patch_function\\n    patch_function(call_original, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\\\", line 240, in patch_with_managed_run\\n    result = patch_function(original, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py\\\", line 303, in fit\\n    return _run_and_log_function(self, original, args, kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/pytorch/_pytorch_autolog.py\\\", line 295, in _run_and_log_function\\n    result = original(self, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\\\", line 445, in call_original\\n    original_result = original(*og_args, **og_kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 842, in run_train\\n    self.run_sanity_check(self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 1107, in run_sanity_check\\n    self.run_evaluation()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 962, in run_evaluation\\n    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py\\\", line 174, in evaluation_step\\n    output = self.trainer.accelerator.validation_step(args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 226, in validation_step\\n    return self.training_type_plugin.validation_step(*args)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 161, in validation_step\\n    return self.lightning_module.validation_step(*args, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/SiameseNetwork.py\\\", line 91, in validation_step\\n    output1, output2 = self(x0, x1)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/modules/module.py\\\", line 889, in _call_impl\\n    result = self.forward(*input, **kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/SiameseNetwork.py\\\", line 79, in forward\\n    output1 = self.forward_once(input1)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/SiameseNetwork.py\\\", line 73, in forward_once\\n    output = self.cnn1(x)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/modules/module.py\\\", line 889, in _call_impl\\n    result = self.forward(*input, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/modules/container.py\\\", line 119, in forward\\n    input = module(input)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/modules/module.py\\\", line 889, in _call_impl\\n    result = self.forward(*input, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/modules/padding.py\\\", line 173, in forward\\n    return F.pad(input, self.padding, 'reflect')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torch/nn/functional.py\\\", line 3995, in _pad\\n    assert len(pad) // 2 <= input.dim(), \\\"Padding length too large\\\"\\nAttributeError: 'str' object has no attribute 'dim'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 17,
    "_metric": "loss",
    "_total_time": 0,
    "_iteration": 44,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1624033352.933963,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2021-06-18_18-22-32",
    "checkpoint_file": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/experiment_state-2021-06-18_18-22-32.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1624033352.933963,
    "timestamp": 1624033392.497325
  }
}