{
  "checkpoints": [
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00001\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.00021941509579481366,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.00021941509579481366,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00021942\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800929.423539,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00001_1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00021942_2021-05-23_22-15-29\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00001_1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00021942_2021-05-23_22-15-29/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44595, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44595, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00009\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 64,\n    \"lr\": 0.095263806816008,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 64,\n    \"lr\": 0.095263806816008,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"9_batch_size=32,layer_1_size=128,layer_2_size=64,lr=0.095264\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800935.1217952,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00009_9_batch_size=32,layer_1_size=128,layer_2_size=64,lr=0.095264_2021-05-23_22-15-35\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00009_9_batch_size=32,layer_1_size=128,layer_2_size=64,lr=0.095264_2021-05-23_22-15-35/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44593, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44593, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00003\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.004411984724599738,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.004411984724599738,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"3_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.004412\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800930.814139,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00003_3_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.004412_2021-05-23_22-15-30\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00003_3_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.004412_2021-05-23_22-15-30/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44590, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44590, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00004\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.009646641719902151,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.009646641719902151,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"4_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0096466\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800932.2292302,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00004_4_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0096466_2021-05-23_22-15-30\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00004_4_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0096466_2021-05-23_22-15-30/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44594, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44594, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00002\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00025031746314944366,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.00025031746314944366,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"2_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00025032\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800930.8015811,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00002_2_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00025032_2021-05-23_22-15-29\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00002_2_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00025032_2021-05-23_22-15-29/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44596, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44596, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00007\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0002810517431692912,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0002810517431692912,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"7_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00028105\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800933.686292,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00007_7_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00028105_2021-05-23_22-15-33\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00007_7_batch_size=64,layer_1_size=32,layer_2_size=64,lr=0.00028105_2021-05-23_22-15-33/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44589, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44589, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00005\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.03700472302014726,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.03700472302014726,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"5_batch_size=128,layer_1_size=128,layer_2_size=256,lr=0.037005\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800932.2392151,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00005_5_batch_size=128,layer_1_size=128,layer_2_size=256,lr=0.037005_2021-05-23_22-15-32\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00005_5_batch_size=128,layer_1_size=128,layer_2_size=256,lr=0.037005_2021-05-23_22-15-32/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44588, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44588, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00008\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.05133889912022567,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.05133889912022567,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"8_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.051339\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800935.1119502,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00008_8_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.051339_2021-05-23_22-15-33\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00008_8_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.051339_2021-05-23_22-15-33/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44591, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44591, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00000\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 128,\n    \"lr\": 0.0006237358987913517,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 128,\n    \"lr\": 0.0006237358987913517,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"0_batch_size=32,layer_1_size=32,layer_2_size=128,lr=0.00062374\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800929.375869,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00000_0_batch_size=32,layer_1_size=32,layer_2_size=128,lr=0.00062374_2021-05-23_22-15-29\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00000_0_batch_size=32,layer_1_size=32,layer_2_size=128,lr=0.00062374_2021-05-23_22-15-29/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44597, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44597, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"9e506_00006\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.06684489741336676,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.06684489741336676,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"6_batch_size=64,layer_1_size=128,layer_2_size=128,lr=0.066845\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621800933.676712,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00006_6_batch_size=64,layer_1_size=128,layer_2_size=128,lr=0.066845_2021-05-23_22-15-32\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_9e506_00006_6_batch_size=64,layer_1_size=128,layer_2_size=128,lr=0.066845_2021-05-23_22-15-32/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44592, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=44592, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 31, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 704, in _run\\n    self.data_connector.prepare_data(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py\\\", line 57, in prepare_data\\n    model.prepare_data()\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 86, in prepare_data\\n    mnist_train = self.download_data(self.data_dir)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/models/LightningMNISTClassifier.py\\\", line 83, in download_data\\n    return KMNIST(data_dir, train=True, download=True, transform=transform)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 79, in __init__\\n    self.download()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 137, in download\\n    if self._check_exists():\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 129, in _check_exists\\n    return (os.path.exists(os.path.join(self.processed_folder,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/torchvision/datasets/mnist.py\\\", line 122, in processed_folder\\n    return os.path.join(self.root, self.__class__.__name__, 'processed')\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/posixpath.py\\\", line 76, in join\\n    a = os.fspath(a)\\nTypeError: expected str, bytes or os.PathLike object, not int\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 1000,
    "_metric": "loss",
    "_total_time": 0,
    "_iteration": 85,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1621800929.2163782,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2021-05-23_22-15-29",
    "checkpoint_file": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/experiment_state-2021-05-23_22-15-29.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1621800929.2163782,
    "timestamp": 1621800929.395607
  }
}