{
  "checkpoints": [
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00004\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 256,\n    \"lr\": 0.00014791273942676612,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 256,\n    \"lr\": 0.00014791273942676612,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"4_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.00014791\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803591.2155478,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00004_4_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.00014791_2021-05-23_22-59-48\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00004_4_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.00014791_2021-05-23_22-59-48/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47270, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47270, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00002\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 256,\n    \"lr\": 0.001180862570602507,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 256,\n    \"lr\": 0.001180862570602507,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"2_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.0011809\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803588.470002,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00002_2_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.0011809_2021-05-23_22-59-45\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00002_2_batch_size=128,layer_1_size=32,layer_2_size=256,lr=0.0011809_2021-05-23_22-59-45/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47273, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47273, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00005\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.001518204117172574,\n    \"batch_size\": 64\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.001518204117172574,\n    \"batch_size\": 64\n  },\n  \"experiment_tag\": \"5_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.0015182\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803591.2233942,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00005_5_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.0015182_2021-05-23_22-59-51\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00005_5_batch_size=64,layer_1_size=64,layer_2_size=128,lr=0.0015182_2021-05-23_22-59-51/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47262, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47262, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00003\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0022787179291570625,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0022787179291570625,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"3_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.0022787\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803588.493417,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00003_3_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.0022787_2021-05-23_22-59-48\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00003_3_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.0022787_2021-05-23_22-59-48/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47269, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47269, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00007\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.07763414010546399,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 256,\n    \"lr\": 0.07763414010546399,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"7_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.077634\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803593.990804,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00007_7_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.077634_2021-05-23_22-59-53\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00007_7_batch_size=32,layer_1_size=128,layer_2_size=256,lr=0.077634_2021-05-23_22-59-53/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47263, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47263, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00000\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.002682329789346582,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 64,\n    \"lr\": 0.002682329789346582,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"0_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0026823\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803585.873129,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00000_0_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0026823_2021-05-23_22-59-45\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00000_0_batch_size=32,layer_1_size=64,layer_2_size=64,lr=0.0026823_2021-05-23_22-59-45/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47258, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47258, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00006\",\n  \"config\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.0002784937400696156,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 64,\n    \"layer_2_size\": 128,\n    \"lr\": 0.0002784937400696156,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"6_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.00027849\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803593.784805,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00006_6_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.00027849_2021-05-23_22-59-51\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00006_6_batch_size=128,layer_1_size=64,layer_2_size=128,lr=0.00027849_2021-05-23_22-59-51/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47266, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47266, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00008\",\n  \"config\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0002750456443812772,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 32,\n    \"layer_2_size\": 64,\n    \"lr\": 0.0002750456443812772,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"8_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00027505\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803596.299566,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00008_8_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00027505_2021-05-23_22-59-53\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00008_8_batch_size=32,layer_1_size=32,layer_2_size=64,lr=0.00027505_2021-05-23_22-59-53/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47272, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47272, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00009\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.002051480772662637,\n    \"batch_size\": 32\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.002051480772662637,\n    \"batch_size\": 32\n  },\n  \"experiment_tag\": \"9_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.0020515\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803596.4838212,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00009_9_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.0020515_2021-05-23_22-59-56\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00009_9_batch_size=32,layer_1_size=128,layer_2_size=128,lr=0.0020515_2021-05-23_22-59-56/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47264, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47264, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"trainable_name\": \"training_function\",\n  \"trial_id\": \"cdb7c_00001\",\n  \"config\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.00011253270724424333,\n    \"batch_size\": 128\n  },\n  \"local_dir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha\",\n  \"evaluated_params\": {\n    \"layer_1_size\": 128,\n    \"layer_2_size\": 128,\n    \"lr\": 0.00011253270724424333,\n    \"batch_size\": 128\n  },\n  \"experiment_tag\": \"1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00011253\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 6,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 0,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"placement_group_factory\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"800595b2000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d947d94288c03435055944b068c03475055944b008c066d656d6f7279944b008c136f626a6563745f73746f72655f6d656d6f7279944b0075618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\"\n  },\n  \"stopping_criterion\": {},\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1621803585.901254,\n  \"logdir\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00001_1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00011253_2021-05-23_22-59-45\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/training_function_cdb7c_00001_1_batch_size=128,layer_1_size=128,layer_2_size=128,lr=0.00011253_2021-05-23_22-59-45/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 702, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 686, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\\\", line 47, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/worker.py\\\", line 1481, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47267, ip=192.168.2.103)\\n  File \\\"python/ray/_raylet.pyx\\\", line 505, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 449, in ray._raylet.execute_task.function_executor\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/_private/function_manager.py\\\", line 556, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 173, in train_buffered\\n    result = self.train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 232, in train\\n    result = self.step()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 366, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 512, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=47267, ip=192.168.2.103)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 248, in run\\n    self._entrypoint()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 315, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/function_runner.py\\\", line 580, in _trainable_func\\n    output = fn()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 339, in _inner\\n    inner(config, checkpoint_dir=None)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/ray/tune/utils/trainable.py\\\", line 330, in inner\\n    trainable(config, **fn_kwargs)\\n  File \\\"/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/src/Main.py\\\", line 36, in training_function\\n    trainer.fit(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 458, in fit\\n    self._run(model)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 756, in _run\\n    self.dispatch()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 797, in dispatch\\n    self.accelerator.start_training(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py\\\", line 96, in start_training\\n    self.training_type_plugin.start_training(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py\\\", line 144, in start_training\\n    self._results = trainer.run_stage()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 807, in run_stage\\n    return self.run_train()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 837, in run_train\\n    self._pre_training_routine()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py\\\", line 822, in _pre_training_routine\\n    self.on_pretrain_routine_start()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py\\\", line 162, in on_pretrain_routine_start\\n    callback.on_pretrain_routine_start(self, self.lightning_module)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 220, in on_pretrain_routine_start\\n    self.__resolve_ckpt_dir(trainer)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py\\\", line 584, in __resolve_ckpt_dir\\n    if isinstance(trainer.logger.version, str) else f\\\"version_{trainer.logger.version}\\\"\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 232, in version\\n    return self.run_id\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 163, in run_id\\n    _ = self.experiment\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 41, in experiment\\n    return get_experiment() or DummyExperiment()\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py\\\", line 49, in wrapped_fn\\n    return fn(*args, **kwargs)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py\\\", line 39, in get_experiment\\n    return fn(self)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py\\\", line 150, in experiment\\n    self._experiment_id = self._mlflow_client.create_experiment(\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/client.py\\\", line 471, in create_experiment\\n    return self._tracking_client.create_experiment(name, artifact_location)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py\\\", line 140, in create_experiment\\n    return self.store.create_experiment(name=name, artifact_location=artifact_location,)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 78, in create_experiment\\n    response_proto = self._call_endpoint(CreateExperiment, req_body)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py\\\", line 55, in _call_endpoint\\n    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 170, in call_endpoint\\n    response = verify_rest_response(response, endpoint)\\n  File \\\"/Users/beantown/opt/anaconda3/envs/PuzzleSolver/lib/python3.8/site-packages/mlflow/utils/rest_utils.py\\\", line 122, in verify_rest_response\\n    raise RestException(json.loads(response.text))\\nmlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Got an invalid experiment name 'Jiggsaw_test'. An experiment name must be an absolute path within the Databricks workspace, e.g. '/Users/<some-username>/my-experiment'. For more information about changes to experiment naming conventions, see 'https://docs.databricks.com/applications/mlflow/experiments.html#experiment-migration'.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 1000,
    "_metric": "loss",
    "_total_time": 0,
    "_iteration": 112,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1621803585.7269812,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2021-05-23_22-59-45",
    "checkpoint_file": "/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results/tune_mnist_asha/experiment_state-2021-05-23_22-59-45.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1621803585.7269812,
    "timestamp": 1621803596.29304
  }
}